## Performance Difference Between Numpy and Python code

In [3]:
import numpy as np 

In [4]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [5]:
# Multiply each by 2
%timeit my_arr* 2

5.93 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit my_list*2

60.9 ms ± 9.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Numpy-based algorithm is much faster than their Python counterparts

## The NumPy ndarray: A Multidimensional Array Object

In [7]:
data = np.array([[1, 2.0, 4],
                 [3.4, 6.4, 1]])
data

array([[1. , 2. , 4. ],
       [3.4, 6.4, 1. ]])

In [8]:
data.ndim

2

In [9]:
data * 10

array([[10., 20., 40.],
       [34., 64., 10.]])

In [10]:
data

array([[1. , 2. , 4. ],
       [3.4, 6.4, 1. ]])

In [11]:
data+data

array([[ 2. ,  4. ,  8. ],
       [ 6.8, 12.8,  2. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4], [5, 6, 7 ,8]]

In [17]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim, arr2.shape

(2, (2, 4))

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
np.empty((3,2,3))

array([[[1.35807731e-312, 0.00000000e+000, 8.95501283e-312],
        [0.00000000e+000, 8.95521402e-312, 8.95521532e-312]],

       [[1.35807731e-312, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.95521532e-312, 8.95521662e-312]],

       [[1.35807731e-312, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.95521662e-312, 8.95521791e-312]]])

In [25]:
np.empty(2, dtype=int)

array([80084992,      422])

In [26]:
import numpy as geek

b = geek.empty(2, dtype = int)
print("Matrix b : \n", b)

a = geek.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = geek.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [119692528       422]

Matrix a : 
 [[ -403063936   234823310]
 [-1241254422  -927912360]]

Matrix c : 
 [[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 7.51e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [27]:
import numpy as np

In [28]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.array((1,2))

array([1, 2])

In [30]:
np.asarray(data1)

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
np.full([3, 3], 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(5, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Data Types for ndarrays

In [34]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [35]:
arr1

array([1., 2., 3.])

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2

array([1, 2, 3])

In [38]:
arr2.dtype

dtype('int32')

You can explicitly convert or cast an array from one data type to another using ndarray’s astype method:

In [39]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [42]:
float_arr = arr.astype(np.float64)

In [43]:
float_arr

array([1., 2., 3., 4., 5.])

In [44]:
float_arr.dtype

dtype('float64')

In [45]:
arr = np.array([1.2, 3.4, 3.0, -2.1])
arr

array([ 1.2,  3.4,  3. , -2.1])

In [46]:
arr.dtype

dtype('float64')

In [47]:
arr.astype(np.int32)

array([ 1,  3,  3, -2])

If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

In [52]:
numeric_strings = np.array(["1.45", "2.2", "1.0"], dtype=np.string_)
numeric_strings

array([b'1.45', b'2.2', b'1.0'], dtype='|S4')

In [56]:
numeric_strings.astype(float).dtype

dtype('float64')

In [57]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
calibers = np.array([.32, .341, .45, .50], dtype=np.float64)
calibers

array([0.32 , 0.341, 0.45 , 0.5  ])

In [59]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
np.zeros(8, dtype="uint32")

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [67]:
np.zeros(8, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0.])

Arithmatic with NumPy Arrays

In [68]:
arr = np.array([[1, 2, 3], [4, 5.0, 6]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [69]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [70]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [72]:
arr  * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [73]:
arr2  = np.array([[1, 4, 5], [0, 4, 9]])
arr2

array([[1, 4, 5],
       [0, 4, 9]])

In [74]:
arr > arr2

array([[False, False, False],
       [ True,  True, False]])

## Basic Indexing and slicing 

In [101]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr[9]

9

In [103]:
arr[5:8]

array([5, 6, 7])

In [104]:
arr[5:8] = 12

In [105]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [106]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [107]:
arr_slice[1] = 100

In [108]:
arr_slice

array([ 12, 100,  12])

In [109]:
arr

array([  0,   1,   2,   3,   4,  12, 100,  12,   8,   9])

In [110]:
arr_slice[:]

array([ 12, 100,  12])

In [111]:
arr_slice[:] = 45

In [112]:
arr

array([ 0,  1,  2,  3,  4, 45, 45, 45,  8,  9])

In [113]:
a = arr_slice

In [115]:
a[:] = 100

In [116]:
a

array([100, 100, 100])

In [117]:
arr_slice

array([100, 100, 100])

In [118]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array—for example, arr[5:8].copy(). As you will see, pandas works this way, too.

In [119]:
a = arr[5:8].copy()
a

array([100, 100, 100])

In [120]:
a[:] = 16

In [121]:
a

array([16, 16, 16])

In [122]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [123]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr2d[2]

array([7, 8, 9])

In [125]:
arr2d[1]

array([4, 5, 6])

In [126]:
arr2d[0][2]

3

In [135]:
arr3d = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [140]:
arr3d[0], arr3d[0].shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [143]:
old_values = arr3d[0].copy()

In [144]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
arr3d[0] = 100

In [146]:
arr3d

array([[[100, 100, 100],
        [100, 100, 100]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [148]:
arr3d[0] = old_values

In [149]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [155]:
arr3d[1, 0], arr3d[0, 1, 0]

(array([7, 8, 9]), 4)

In [156]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [157]:
arr[1:6]

array([  1,   2,   3,   4, 100])

In [160]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
arr2d[1:2]

array([[4, 5, 6]])

In [164]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [165]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [169]:
arr2d[0:2, :2]

array([[1, 2],
       [4, 5]])

In [170]:
arr2d[1, :2]

array([4, 5])

In [172]:
arr2d[2, :2]

array([7, 8])

In [175]:
arr2d[:2, 1:] = 0

In [176]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [177]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [178]:
data

array([[1. , 2. , 4. ],
       [3.4, 6.4, 1. ]])

In [179]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [180]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [181]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [182]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [184]:
data[names == "Joe"]

array([[  0,   2],
       [-12,  -4],
       [  3,   4]])

In [185]:
data[names == 'Bob', 1:]

array([[7],
       [0]])

In [186]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [187]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [188]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [190]:
cond = names == 'Bob'

In [194]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [196]:
mask = (names == 'Bob') |(names == 'Will')

In [197]:
mask

array([ True, False,  True,  True,  True, False, False])

In [198]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [199]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [202]:
data[data < 0] = 0

In [203]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [206]:
data[names != 'Joe'] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## Fancy Indexing

In [211]:
arr = np.zeros((8, 4))

In [212]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [216]:
for i in range(8):
    arr[i] = i

In [217]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [219]:
arr[[4, 0, 3, 2]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [224]:
arr[[-1, -3, -5]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [231]:
arr = np.arange(32).reshape((8, 4))

In [232]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [234]:
arr[1]

array([4, 5, 6, 7])

In [236]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [239]:
arr[[1, 5, 7, 1]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [240]:
arr[[1, 5, 7, 1]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 4,  7,  5,  6]])

## Transporting Arrays and Swapping Axes

In [246]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [247]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [254]:
np.arange(100).reshape((4, 5, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [255]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])


In [263]:
arr, arr.shape

(array([[ 0,  1,  0],
        [ 1,  2, -2],
        [ 6,  3,  2],
        [-1,  0, -1],
        [ 1,  0,  1]]),
 (5, 3))

In [264]:
arr.T, arr.T.shape

(array([[ 0,  1,  6, -1,  1],
        [ 1,  2,  3,  0,  0],
        [ 0, -2,  2, -1,  1]]),
 (3, 5))

In [260]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [261]:
np.dot(arr, arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [265]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [266]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [268]:
arr.swapaxes(1,0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Pseudorandom Number Generation